export {
  currentWorkspaceScopeKey,
  currentWorkspaceEnv,
  getWslHome,
  isLocalHost,
  LOCAL_WORKSPACE,
  sameWorkspaceEnv,
  workspaceSelectionOpensNewTerminal,
  workspaceDisplayLabel,
  useWorkspaceEnvStore,
  workspaceScopeKey,
  type WorkspaceEnv,
  type SshWorkspaceProfile,
  type WslDistro,
} from "./env";
